baseURL = "https://meirongdev.github.io/slides/"
languageCode = 'en-us'
title = 'Meirong Dev Slides'

theme = ["github.com/joshed-io/reveal-hugo"]

[markup.goldmark.renderer]
unsafe = true

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true

[params.reveal_hugo]
custom_css = "css/custom.css"

